version: '3'
services:
  php-web:
    container_name: php_71_web
    image: php-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /src:/data/webapp